### ISSUE TITLE
Some questions about lib

### ISSUE THREAD

**Issue by goriunov** [snapview/tungstenite-rs#42] opened 2018-07-11 11:13 UTC
Hi, sorry for may be newbie questions, i am quite new to the Rust but i have a lot of experience working with websockets in JS. I would appricaiate if you could answer few questions. 

**1.** I am not sure how threading works but do i understand right that for each new connection will be created a new thread ?  And how many connection do you think ( approximately ) simple 1 core 2 gb ram server can handle.

**2.** How can i created  broadcast system, where i send messages to all connected websockets (or may be to only specific one).

**3.** What about using multi core ? Would it automatically scale across all available CPU on the pc and would it be able to communicate between websokcets connected to different CPU (JS has problems with that so you have to manually implement this system).

**4.** Are you planning to add more examples and benchmarks. I would really like to see some benchmarks against different Rust websocket implementation (may be not just Rust).

The library looks cool, but does not have enough information for newcomers like me. Thank you :)

**Comment by agalakhov** [comment] 2018-07-11 12:00
Hi,

1. It's up to you, and we try to make a solution that fits all. Tungstenite is very flexible and does not make any assumptions about threading. You are free to use it simply in one thread per connection, or in a poll-select loop i.e. using the `mio` crate, or in green threads using `tokio` and the `tokio-tungstenite` binding. If you need "just" ordinary multiple connection handling and don't care about threading, I'd recommend using Tokio. Tungstenite was designed with performance in mind and with `mio` or `tokio` should be able to handle at least up to 10000s of connections on a server you described, provided that messages are small enough to fit in memory. Expect the bottleneck either at network level or in the application code, not in Tungstenite.

2. Just maintain a list of sockets you want to send to and iterate over it. The straightforward solution.

3. Tungstenite itself does only fo the protocol. The easiest way to do efficient multitasking is Tokio (the `tokio` crate, see also `futures`). It has an executor with a scalable thread pool approach and thus is able to use all cores. We provide a binding for Tokio called `tokio-tungstenite`. If you want manual fine-grained control over threads to handle extreme loads, `mio` would provide you with a portable poll/select loop.

4. We could benchmark websocket messaging, but what you want is probably benchmarking of the thread pool. The thread pool of Tokio is very fast.

Comparing with `ws-rs`:
- Processing of a single message takes about the same time or just a little bit faster in Tungstenite. Difference is very little.
- Tungstenite adheres to the standard more strict than `ws-rs`. In Autobahn test only two testcases are "non-strict", and both are related to incorrect UTF-8. We plan to go 100% strict in the future versions.
- `ws-rs` processes all messages in a single thread with poll/select loop, while Tokio is able to use as many cores as you want. This makes `tokio-tungstenite` more scalable than `ws-rs`.
- Tungstenite does NOT currently support permessage-deflate (it's planned). `ws-rs` does, but it's implemented as a plugin and is not enabled by default.
- Tungstenite is modular so that those who wants to invent their own wheel could reuse some components of Tungstenite for it.

We wrote Tungstenite as ws-rs did not work for us good enough mostly due to its threading issues. Our company uses Tungstenite in production for realtime image transfer, and we observed no performance issues at this particular component.

**Comment by goriunov** [comment] 2018-07-12 06:02
Thank you for your response :)

**Comment by application-developer-DA** [comment] 2018-07-18 10:31
I'm closing this issue as it seems that the initial questions have been answered. Please re-open / open a new one if something is still unclear.

**Closed by application-developer-DA** 2018-07-18 10:31 UTC
Labels: question
