### ISSUE TITLE
option to allow invalid certs

### ISSUE THREAD

**Issue by dbregman** [snapview/tungstenite-rs#218] opened 2021-07-12 15:05 UTC
Yes, this is already possible in various ways, but it is unacceptably cumbersome.

I receive financial data through a websockets connection and this morning due to an issue with the data provider I couldn't connect. They told me I would need to allow invalid certs to workaround the issue. Should be simple, right? But I wasn't able to get the data working in time.

In the end it took almost an hour to figure out. The solution I came up with is copying the entire code for connect() out of the library and adding the `connector_builder.danger_accept_invalid_certs(true);` . It takes 100 lines of code!

Frankly this is nuts. Every other websockets library I've used in other languages has a simple option you can pass to do this.

If you were assuming that it's totally fine to make it difficult because it's discouraged/bad practices/whatever, this is your counterexample.

**Comment by application-developer-DA** [comment] 2021-07-12 16:02
Duplicate of https://github.com/snapview/tungstenite-rs/issues/84.

**P.S.**

> In the end it took almost an hour to figure out. The solution I came up with is copying the entire code for connect() out of the library and adding the connector_builder.danger_accept_invalid_certs(true); . It takes 100 lines of code! Frankly this is nuts.

The one could fork `tungstenite-rs`, add one line of code to allow invalid certs and just change a single line of code in the `Cargo.toml` to use the forked version 😉 (so that once the hack is not required, a simple `git-revert` in the app's repo reverts the dependenc => lots of time saved, less changes in all places, cleaner history)

**Closed by application-developer-DA** 2021-07-12 16:02 UTC

**Comment by dbregman** [comment] 2021-07-12 16:42
If you're going to close an issue you should state why it's being closed. The other issue that it's a dup of is also closed w/o giving any reason.

I am guessing you closing it implies WONTFIX, but how is that justified? Not having an option for this is problematic, as demonstrated, and it's completely out of step with every other websockets lib I've used in other languages.

PS.
Forking doesn't save any time at all, copy pasting is faster. The time is figuring it out. Not everyone is an expert on these libs and knows in 5 minutes what to do.
