### ISSUE TITLE
Suggestion: Follow HTTP 3xx redirects

### ISSUE THREAD

**Issue by Redrield** [snapview/tungstenite-rs#139] opened 2020-09-07 23:21 UTC
RFC 6455 states that clients may follow HTTP 3xx redirects in response to a websocket handshake, while it's not required by the standard, it would be a useful thing to add.

**Comment by application-developer-DA** [comment] 2020-09-10 10:01
@Redrield , thanks for the suggestions (we actually have this in our pipeline, but unfortunately we've never found some time to implement it). I'm going to close this one as it seems to be a duplicate of https://github.com/snapview/tungstenite-rs/issues/46 as pointed out by @bsergean

**Closed by application-developer-DA** 2020-09-10 10:01 UTC
Labels: enhancement
